spring:
  main.banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      jdbc.time_zone: UTC
  sql:
    init:
      mode: always

  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:ewm-main"
    username: "service"
    password: "service"

logging:
  level:
    org.springframework:
      orm.jpa: WARN
      orm.jpa.JpaTransactionManager: WARN
      transaction: WARN
      transaction.interceptor: WARN
